name: Update README

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch GitHub Stats
        run: |
          require('dotenv').config();
          const axios = require('axios');
          const fs = require('fs');
          const execSync = require('child_process').execSync;

          const username = 'imanhedeshy'; 
          const token = '${{ secrets.GH_TOKEN }}';

          const headers = {
            'Authorization': `bearer ${token}`,
            'Content-Type': 'application/json',
          };

          // ... (rest of your YAML content)

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
